FROM maven:3.9.8-amazoncorretto-17 AS build

WORKDIR /track/

COPY pom.xml ./

COPY .mvn .mvn

COPY src ./src

RUN mvn clean package

FROM eclipse-temurin:17.0.5_8-jre-focal

LABEL Description="Workload service system" Version="0.0.1"

ARG VERSION=0.0.1

WORKDIR /app/

COPY --from=build /track/target/track-gym-app-1.0-SNAPSHOT.jar app.jar

EXPOSE 8083

ENTRYPOINT ["java", "-jar", "app.jar"]