spring:
  application:
    name: workload-service

server:
  port: 8083

#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        concurrency: 3
#        max-concurrency: 2
#        prefetch: 1

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:monitoringdb;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: epam.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    prometheus:
      access: read_only
    metrics:
      access: read_only
  metrics:
    tags:
      application: workload-service
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    epam.workload: DEBUG
  file:
    name: logs/workload-service.log


spring.config.activate.on-profile: docker